services:
  - type: web
    name: ironman-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    plan: free
    envVars:
      - key: ODDS_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: CORS_ORIGIN
        sync: false